worker_processes 1;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 128;
}

http {
    include       /etc/nginx/mime.types;
    default_type  text/html;
    sendfile      on;
    keepalive_timeout 30;
    access_log    /var/log/nginx/access.log;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /version {
            default_type text/plain;
            alias /usr/share/nginx/html/version.txt;
        }
    }
}
